- name: Install System Packages 1
  package:
    name:
      - build-essential
      - cmake
      - pkg-configc
      - libpthread-stubs0-dev
    state: present
  tags:
    - install
    - neovim
    - core
  when: ansible_os_family == "Ubunutu"

- name: Install System Packages 2
  package:
    name:
      - gettext
      - lua5.1
      - libtool
      - libtool-bin
      - unzip
    state: present
  tags:
    - install
    - neovim
    - core
  when: ansible_os_family == "Ubunutu"
