- name: Installing Stow
  apt: name=stow
  become: true
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning dofiles
  ansible.builtin.git:
    repo: 'git@github.com:pjdietz/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: no
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

