- name: Install Stow
  package:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning dofiles
  git:
    repo: 'git@github.com:pjdietz/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: false
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd "{{ lookup('env', 'HOME') }}/dotfiles" && ./install
  become: false
  tags:
    - install
    - dotfiles
    - stow
