- name: Remove Neovim
  shell: "rm -rf {{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: 'https://github.com/neovim/neovim.git'
    dest: "{{ lookup('env', 'HOME') }}/neovim"
    version: stable
  tags:
    - install
    - neovim
- name: Build Neovim
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make CMAKE_BUILD_TYPE=Release -j 20"
  tags:
    - install
    - neovim
- name: Install Neovim
  become: true
  shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
  tags:
    - install
    - neovim
