- name: Install packages
  package:
    # TODO: extract cargo install and add cargo install tree-sitter-cli
    name:
      - bat
      - fzf
      - ripgrep
      - tmux
      - tree
      - xh
      - zoxide
    state: present
  tags:
    - install
    - productivity
