- name: Install ZSH
  apt: name=zsh
  become: true
  tags: &tags_for_zsh [ "install", "productivity", "dotfiles", "zsh" ]

- name: Change shell to ZSH
  shell: chsh -s $(which zsh)
  become: true
  tags: *tags_for_zsh
