- name: Install ZSH
  package:
    name: zsh
    state: present
  register: zsh_present
  tags:
    - install
    - dotfiles
    - zsh

- name: Change shell to ZSH
  shell: chsh -s /bin/zsh
  become: false
  when: zsh_present.changed
  tags:
    - install
    - dotfiles
    - zsh
